f2fs-tools: fix build failure on mac
external/f2fs-tools/lib/libf2fs.c:1019:12: error: use of undeclared identifier 'BLKFLSBUF'
 1019 |         ioctl(fd, BLKFLSBUF);
      |                   ^~~~~~~~~

Fixes: c188a3e303d9 ("f2fs-tools: invalidate block device page cache before reading metadata")
Reviewed-by: Chao Yu <chao@kernel.org>
Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>